classdef FlowEntity < Entity
    %UNTITLED8 Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        % Identifers below are generated by <FlowEntityBuilder>.
        LocalIdentifier;
        GlobalIdentifier;
    end

    properties (Dependent)
        Parent;     % see also <SliceEntity>
    end
    
    methods (Access = ?FlowEntityBuilder)
        function this = FlowEntity(time_arrive, time_serve, src, varargin)
            this@Entity(time_arrive,time_serve,src,varargin{:});
        end
    end
    
    methods
        %%%
        % Flow Enity's parent is the same as the <FlowEntiyBuilder> object's parent, which
        % is a <SliceEntity> object.
        function p = get.Parent(this)
            p = this.Builder.Parent;
        end
    end
end

