%% Flow Entity
%% Class
% * _copyElement_: no handle class member, thus no need to override this method.
classdef FlowEntity < Entity
    properties
        % Identifers below are generated by <FlowEntityBuilder>.
        LocalIdentifier uint64;
        GlobalIdentifier uint64;
    end
    
    properties (Dependent)
        Parent;     % see also <SliceEntity>
    end
    
%     methods (Access = ?FlowEntityBuilder)
    methods
        function this = FlowEntity(time_arrive, time_serve, src, ...
                local_id, flow_id, varargin)
            if nargin == 0
                arg_list = {};
            else
                arg_list = [{time_arrive, time_serve, src}, varargin];
            end
            this@Entity(arg_list{:});
            if ~isempty(flow_id)
                for i = length(this):-1:1
                    this(i).GlobalIdentifier = flow_id(i);
                end
            end
            for i = length(this):-1:1
                this(i).LocalIdentifier = local_id(i);
            end
        end
    end
    
    methods
        %%%
        % Flow Enity's parent is the same as the <FlowEntiyBuilder> object's parent, which
        % is a <SliceEntity> object.
        function p = get.Parent(this)
            p = this.Builder.Parent;
        end
    end
end

